### ISSUE TITLE
[bug] Embed note would also show the banner; no banner in Readinig mode

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pexels-banner#14]
Tested in Snadbox vault, and found out those issues:

1. If I embed another note in current note, **the embeded block will also show the banner** of current note:

for example:
```md
in a.md:

![[b.md]]

a & b would both show the banners.
```

![image](https://github.com/user-attachments/assets/c4f7951c-1ac5-4bcd-9ac5-4f277ee20a41)

2. When switching to reading view, banner will disappear:

![image](https://github.com/user-attachments/assets/3501d3fc-b14c-49e8-b406-55315166209f)

**Comment by jparkerweb** [comment]
@Moyf  please update the plugin 😀

**Comment by Moyf** [comment]
> @Moyf please update the plugin 😀 Fixed version is `1.3.1`

Updated and it works! Great, Thanks!! 🥳

**Comment by Moyf** [comment]
> @Moyf please update the plugin 😀 Fixed version is `1.3.1`

After updating the Banner became _sticky_ (willll always show), I prefer the previous style (move to top when scrolling), is there any way to change it? Or could it be an optional setting?
