### ISSUE TITLE
Banner div inserted outside of the note content in the DOM

### ISSUE THREAD

**Issue by zui097** [jparkerweb/pexels-banner#17]
The banner image is behind the content. In your example (and as it would be better) the content starts after the image.

<img width="707" alt="2024-10-17_11h54_18" src="https://github.com/user-attachments/assets/3018b1e5-3bcf-491b-8284-963cb72f0dee">

I'm using Obsidian v1.7.4 with a test vault without any other plug-ins and the default theme.

**Comment by Moyf** [comment]
I also mentioned it in https://github.com/jparkerweb/pexels-banner/issues/14#issuecomment-2415498188
(But I'm not sure is it visible in a closed issue 🤔

**Comment by jparkerweb** [comment]
I the banner image has always been rendered behind the note's content, but is note content is usually pushed down a bit. It looks like there is was a bug introduced where the banner image div is being inserted into the page in the wrong place.  I'm looking into it and hope to have a fix out in a day or two.

**Comment by jparkerweb** [comment]
progress update:
- I have custom a global, custom, and per note property developed that will allow you to specify the number of pixels down the screen before the note "content" will start.
- support for Obsidian 1.72+ has been added ([deferred views](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views))
- embedded note banners have been removed while adding/fixing the above, and will hopefully be added back soon. If I can't get them working in a timely manner I may roll forward with the above two updates and address embeds afterwards.

@Moyf @zui097 either of you have an opinion?
_this has been quite a complicated change so far with Obsidian's new way of rendering views now_

**Comment by jparkerweb** [comment]
will address Embedded issues as a separate release.
version 1.4.0 is out now.

thanks for your patience

**Comment by zui097** [comment]
Great, works for me!

**Comment by jparkerweb** [comment]
@zui097 @Moyf 
I just release [v1.4.1](https://github.com/jparkerweb/pexels-banner/releases/tag/1.4.1)
Update to the latest in Obsidian to fix the Embedded note Banner regression issue 🥳
