### ISSUE TITLE
Allow for fit or contain settings

### ISSUE THREAD

**Issue by connradolisboa** [jparkerweb/pexels-banner#18]
Thansk for the plugin. I'm using it to display the covers of my book notes. The problem is that because of how the images are, the banner displays a very pixaleted zoom of it. If there was a property that allowed us to choose between filling (the current choice) or fitting.

**Comment by jparkerweb** [comment]
I can implement this by using:

```css
background-size: contain;
background-repeat: no-repeat;
```

**Comment by KaiserLycan** [comment]
Hey! I really like your plugin, I've been using it for almost month now. I just have a few suggestions though. Is there a way I can customize the margin between the banner and the content without me needing to go to the css? I wanted to push my content down a little bit for personal preference.

Also I have this issue with the backlink note preview, it shows the banner (which I really like), but I want it to be separated from the contents and not overlay on top of each other like this:
![image](https://github.com/user-attachments/assets/4c86cf64-5352-481f-a2ba-f7cf29918cbd)

**Comment by jparkerweb** [comment]
@KaiserLycan your "margin" suggestion was implemented earlier today 🤣, yes I have a time machine:
https://github.com/jparkerweb/pexels-banner/releases/tag/1.4.1

The feature is called "Content Start Position", and you can set global, per folder, and per note inheritance rules for it!

**Comment by KaiserLycan** [comment]
Thanks! I just noticed that I was updated not a minute ago, that's why I edited my original comment 🤣.

**Comment by jparkerweb** [comment]
@connradolisboa 
here you go!!!!!!!!

https://github.com/jparkerweb/pexels-banner/releases/tag/1.5.0

update in Obsidian
