### ISSUE TITLE
[FR] Customize the property name

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pexels-banner#7]
It's a really nice plugin! Thanks for developing!

Would you please consider adding an option in Plugin settings to let user customize the property name (for example, from `pexel-banner` to `image` )?

I used to use `Banners` plugin and it's broken sometimes, so I stop using it, but there are still some `image` properties remains in my vault.

If this property name could be changed, then I can re-use 'em  ; )

**Comment by jparkerweb** [comment]
thanks for the idea, I added this feature
https://github.com/jparkerweb/pexels-banner/releases/tag/1.2.0

you should be able to update the plugin now :)

**Comment by jparkerweb** [comment]
![image](https://github.com/user-attachments/assets/28a7b0a3-8389-4b1b-ab37-b719f5364819)

**Comment by Moyf** [comment]
> ![image](https://private-user-images.githubusercontent.com/3073864/375979344-28a7b0a3-8389-4b1b-ab37-b719f5364819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODM1NzEsIm5iZiI6MTcyODc4MzI3MSwicGF0aCI6Ii8zMDczODY0LzM3NTk3OTM0NC0yOGE3YjBhMy04Mzg5LTRiMWItYWIzNy1iNzE5ZjUzNjQ4MTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMDEzNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEzZmUyNDE4Njk4NzhiNDJmMzcwNjAyMWFkODZlY2E4MTQxODIwNTM3NDRhNDZkYzc4ZDI3NDVmNzdhYzUxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.quM8PeeB61GdxZEEaMNhaEnJBbJjr3Hix9Jc_CwLhBE)

That's really a surprise, so quick! Thanks!
