### ISSUE TITLE
[FR] Define banner for a folder

### ISSUE THREAD

**Issue by Moyf** [jparkerweb/pexels-banner#8]
Hello!  
Is it possible to define a "Pexel banner property" for an entire folder instead of for individual notes?  

If that’s the case, for instance, users could assign a banner to all Daily Notes without having to add properties to each one individually!

**Comment by jparkerweb** [comment]
added:
https://github.com/jparkerweb/pexels-banner/releases/tag/1.3.0

update the plugin 😀

![image](https://github.com/user-attachments/assets/a637f365-0286-4590-a8c1-34cb734b0669)

**Comment by Moyf** [comment]
> added: https://github.com/jparkerweb/pexels-banner/releases/tag/1.3.0
> 
> update the plugin 😀
> 
> ![image](https://private-user-images.githubusercontent.com/3073864/375986222-a637f365-0286-4590-a8c1-34cb734b0669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3ODM1NDcsIm5iZiI6MTcyODc4MzI0NywicGF0aCI6Ii8zMDczODY0LzM3NTk4NjIyMi1hNjM3ZjM2NS0wMjg2LTQ1OTAtYThjMS0zNGNiNzM0YjA2NjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTNUMDEzNDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJlMDVmZjg4NDg5MDg1NzYyYTFhNjRiYjRkOGNhMjFjMjFjYzg0YjQ0ZDZlYTNlZmY1YTMyYmM4MjBmMGZkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dnPC83cPOw4WL9QKa0LsN4JK5DWCHSxxdvnGv1RavlU)

Amazing, thank you!!
